### ISSUE TITLE
Fails on lv2.h

### ISSUE THREAD

**Issue by badosu** [manuels/cxx2rs#4]
I am experimenting on Rust as an audio processing language, so I am trying to create a simple [lv2 plugin](http://lv2plug.in/pages/why-lv2.html).

The problem is that I am not able to process the header file to access lv2 interface, see:

This is the file: [lv2.h](http://lv2plug.in/git/cgit.cgi/lv2.git/plain/lv2/lv2plug.in/ns/lv2core/lv2.h)

```
~/l/amp ❯❯❯ python2.7 ~/Code/cxx2rs/cxx2rs.py lv2 /usr/include/lv2.h

#![crate_type = "lib"]
#![crate_name = "ssh"]

extern crate libc;
use std::mem;

use std::collections::enum_set::CLike;


Traceback (most recent call last):
  File "/home/badosu/Code/cxx2rs/cxx2rs.py", line 74, in <module>
    main()
  File "/home/badosu/Code/cxx2rs/cxx2rs.py", line 47, in main
    print "/*\n%s*/" % stringify_function_declaration(func)
  File "/home/badosu/Code/cxx2rs/stringify.py", line 21, in stringify_function_declaration
    canonical_function_name(node),
  File "/home/badosu/Code/cxx2rs/parser.py", line 94, in canonical_function_name
    for p in parent_path(node):
  File "/home/badosu/Code/cxx2rs/parser.py", line 89, in parent_path
    res = parent_path(parent) + [parent]
  File "/home/badosu/Code/cxx2rs/parser.py", line 86, in parent_path
    if parent.spelling is None:
AttributeError: 'NoneType' object has no attribute 'spelling'
```

**Comment by manuels** [comment]
I just pushed a new commit and tried compiling lv2.h. Worked fine here.

**Comment by badosu** [comment]
I am sorry, i just pulled fab40a86fc65b9f003bb2f89e019a44f431c5185, and it still fails for me, see [the gist](https://gist.github.com/badosu/1a7515b837372fb00ea1).

Am I doing anything wrong?

**Comment by manuels** [comment]
hmm, what does `clang --version` output on your system?

**Comment by badosu** [comment]
Hi @manuels, it follows:

```
~ ❯❯❯ clang --version
clang version 3.5.1 (tags/RELEASE_351/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by manuels** [comment]
$ clang --version
    Debian clang version 3.5.0-1~exp1 (trunk) (based on LLVM 3.5.0)
    Target: x86_64-pc-linux-gnu
    Thread model: posix

That is pretty strange!

**Comment by badosu** [comment]
Is your version different? If you tell me which is, I can use it to make it work :-). Thanks for helping me out on whis issue.
